pull_request_rules:
  - name: Automatic merge on approval and label
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:merge"
      - status-success=scalafmt
      - status-success=tests
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge for scala steward
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "author=scala-steward"
      - status-success=scalafmt
      - status-success=tests
    actions:
      merge:
        method: squash
        strict: true