queue_rules:
  - name: default
    conditions: # to merge
      - "check-success=Formatting"
      - "check-success=Tests"

pull_request_rules:
  - name: Automatic merge on approval and label
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
      - "check-success=Formatting"
      - "check-success=Tests"
    actions:
      queue:
        name: default
        method: squash

  - name: Automatic merge for scala steward
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "author=scala-steward"
      - "check-success=Formatting"
      - "check-success=Tests"
    actions:
      queue:
        name: default
        method: squash
