queue_rules:
  - name: duplicated default from Automatic merge for scala steward
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
      - "check-success=Formatting"
      - "check-success=Tests"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "author=scala-steward"
      - "check-success=Formatting"
      - "check-success=Tests"
    merge_conditions: []
    merge_method: squash
    method: squash
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
      - "check-success=Formatting"
      - "check-success=Tests"
    merge_conditions: # to merge
      - "check-success=Formatting"
      - "check-success=Tests"
    merge_method: squash

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
