pull_request_rules:
  - name: Automatic merge on approval and label
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:merge"
      - "check-success~=^CI.*Formatting"
      - "check-success~=^CI.*Tests"
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge for scala steward
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "author=scala-steward"
      - "check-success~=^CI.*Formatting"
      - "check-success~=^CI.*Tests"
    actions:
      merge:
        method: squash
        strict: true

  - name: Automatic merge for dependabot
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "author~=^dependabot(|-preview)\[bot\]$"
      - "check-success~=^CI.*Formatting"
      - "check-success~=^CI.*Tests"
    actions:
      merge:
        method: squash
        strict: true
