codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

# https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default:
        informational: true
        if_ci_failed: success
    patch:
      default:
        informational: true
        if_ci_failed: success

flags:
  scala-it-2.12:
    paths:
      - *
    carryforward: true
  scala-it-2.13:
    paths:
      - *
    carryforward: true

ignore:
  - "**/S3MetaInfo.scala"