codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

# https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default:
        informational: true
        if_ci_failed: success
    patch:
      default:
        informational: true
        if_ci_failed: success

flags:
  all-scala-2.12:
    paths:
      - box/src/main/scala/blobstore/box/BoxPath.scala
      - box/src/main/scala/blobstore/box/BoxStore.scala
      - core/src/main/scala/blobstore/PathStore.scala
      - url/src/main/scala/blobstore/url/Path.scala
    carryforward: true
  all-scala-2.13:
    paths:
      - box/src/main/scala/blobstore/box/BoxPath.scala
      - box/src/main/scala/blobstore/box/BoxStore.scala
      - core/src/main/scala/blobstore/PathStore.scala
      - url/src/main/scala/blobstore/url/Path.scala
    carryforward: true

ignore:
  - "**/S3MetaInfo.scala"