codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

# https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default:
        informational: true
        if_ci_failed: success
    patch:
      default:
        informational: true
        if_ci_failed: success

flags:
  scala-it:
    paths:
      - *
    carryforward: true

ignore:
  - "**/S3MetaInfo.scala"