version: "2"

services:
  hoster:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

  sftp-container:
    image: atmoz/sftp

    volumes:
      - ./tmp/sftp-store-root:/home/blob

    command: "blob:password:::sftp_tests"

  sftp-no-chroot-container:
    image: atmoz/sftp

    volumes:
      - ./tmp/sftp-store-root:/home/blob
      - ./sftp/src/test/resources/sshd_config:/etc/ssh/sshd_config

    command: "blob:password:::sftp_tests"

  minio-container:
    image: minio/minio

    environment:
      - MINIO_ACCESS_KEY=my_access_key
      - MINIO_SECRET_KEY=my_secret_key

    volumes:
      - ./tmp/s3-store-root:/data

    command: "server --compat /data"

  azurite-container:
    image: mcr.microsoft.com/azure-storage/azurite

    volumes:
      - ./tmp/azure-store-root:/data

    command: "azurite-blob --blobHost 0.0.0.0 --loose"