---
version: "2"

services:
  sftp:
    image: atmoz/sftp

    volumes:
      - ./tmp/sftp-store-root:/home/blob

    command: "blob:password:::sftp_tests"

  sftp-no-chroot:
    image: atmoz/sftp

    volumes:
      - ./tmp/sftp-store-root:/home/blob
      - ./sftp/src/test/resources/sshd_config:/etc/ssh/sshd_config

    command: "blob:password:::sftp_tests"

  minio:
    image: minio/minio

    environment:
      - MINIO_ACCESS_KEY=my_access_key
      - MINIO_SECRET_KEY=my_secret_key

    volumes:
      - ./tmp/s3-store-root:/data

    command: "server --compat /data"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite

    volumes:
      - ./tmp/azure-store-root:/data

    command: "azurite-blob --blobHost 0.0.0.0 --loose"

  sbt:
    image: hseeberger/scala-sbt:8u171_2.12.6_1.2.1

    entrypoint: /usr/bin/sbt
    working_dir: /opt/app

    volumes:
    - ~/.sbt:/root/.sbt
    - ~/.ivy2:/root/.ivy2
    - ~/.coursier:/root/.coursier
    - .:/opt/app

    links:
      - sftp:sftp-container
      - sftp-no-chroot:sftp-no-chroot
      - minio:minio-container
      - azurite:azurite-container