addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.8.1")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.7")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.28")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.17")
addSbtPlugin("com.47deg"                 % "sbt-microsites" % "1.3.2")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.2.21")
