addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.5")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.25")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.16")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.2.17")
