addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.9.3")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.10")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.34")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.3.0")
